version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jekyll
    versions:
    - 3.8.5
    - 3.9.0
    - 3.9.0
    - 3.9.0
  - dependency-name: jekyll-feed
    versions:
    - 0.11.0
    - 0.15.1
    - 0.15.1
    - 0.15.1
  - dependency-name: github-pages
    versions:
    - "202"
    - "211"
    - "212"
    - "213"
  - dependency-name: minima
    versions:
    - 2.5.1
    - 2.5.1
    - 2.5.1
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
