version: 2

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_production:
          filters:
            branches:
              only:
                - master

jobs:
  deploy_production:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - deploy:
          command: bash .circleci/setup-heroku-production.sh
      - deploy:
          command: echo "done"
